### ISSUE TITLE
How to choose different algorithms for training

### ISSUE THREAD

**Issue by CDM1619** [ZifanWu/MAG#1]
Thank you for your excellent open source code. I would like to ask for advice on how to switch algorithms, such as running them separately under MAMBA and MAG algorithms

**Comment by ZifanWu** [comment]
Sorry for the late reply. To use MAMBA, just set [`use_MPCmodel`](https://github.com/ZifanWu/MAG/blob/38c6f464ff6db25df04f3be2d358690789eb1f52/src/configs/dreamer/DreamerLearnerConfig.py#L55) to False.

**Comment by CDM1619** [comment]
Thanks for your answer, It works for me.
Can both MAG and MAMBA algorithms be used only in discrete action spaces and not in continuous action spaces? If I want to use these two algorithms in continuous action space, how should I modify them?
Thanks!

**Comment by ZifanWu** [comment]
In principle, MAG and MAMBA are both based on DreamerV2 which is capable of dealing with continuous control problems, but I haven't tried it before. You can refer to the DreamerV2 [paper](https://arxiv.org/abs/2010.02193) and [code](https://github.com/danijar/dreamerv2) for instructions.
